markdown: rdiscount
permalink: /:title/
url: http://blog.zuozhiwei.org
name: 左志伟
author: 左志伟
description: 左志伟的博客
qq: 1123665434
email: zuozhiwei0@gmail.com
duoshuo: zuozhiwei
beian: 冀ICP备16000831号
weibo: 5406636502?s=6uyXnP
github: https://github.com/zuozhiwei
pygments: true
safe: true
paginate: 20
about: "这里是 左志伟 的个人博客，创建于 2016 年。<br/>开始记录自己学习和心得……"
